import Header from "@/components/header/header";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/components/providers/providers";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="md:w-1/2 sm:w-full  max-[600px]:p-3 center m-auto  dark:bg-dark-black bg-zinc-200">
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
      <script
        async
        src="https://www.googletagmanager.com/gtag/js?id=3644927"
      ></script>
      <script
        dangerouslySetInnerHTML={{
          __html: `
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());
   gtag('config', '3644927');`,
        }}
      ></script>
    </html>
  );
}
