import Header from "@/components/header/header";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="md:w-1/2 sm:w-full max-[600px]:p-3 center m-auto ">
        <Header />
        {children}
      </body>
    </html>
  );
}
